markdown: kramdown
highlighter: pygments
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

name: Ed Hughes
url: http://fredmeews.github.io
author:
  name: Ed Hughes
  email: eph123@hughes2000.com


# Enable redirect /rss => feedburner
gems:
  - jekyll-redirect-from